### ISSUE TITLE
basehagraph:  Unable to process binding "text: function(){return error }"

### ISSUE THREAD

**Issue by Nabla128k** [tjntomas/HADashboard-widgets#19]
Hi, I am trying to run basehagraph on HA 0.116.4 and AppDaemon cloned from github master repo..
I hope I have every file at place, config changed to my sensor and trying the simple single value widget from readme...
I got this in browser console:

jquery-3.1.1.min.js:2 jQuery.Deferred exception: Unable to process binding "text: function(){return error }"
Message: error is not defined ReferenceError: Unable to process binding "text: function(){return error }"
Message: error is not defined
    at text (eval at parseBindingsString (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:68:172), <anonymous>:1:57)
    at update (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:98:202)
    at a.B.i (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:72:379)
    at Function.Qc (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:51:391)
    at Function.Rc (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:51:155)
    at Function.aa (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:50:502)
    at Object.a.m.a.B (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:49:67)
    at http://10.8.0.10:5050/javascript/knockout-3.4.1.js:72:366
    at Object.q (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:11:244)
    at m (http://10.8.0.10:5050/javascript/knockout-3.4.1.js:71:428) undefined

Can you help me please what's wrong?
(chart widget is empty and other widgets won't load values)

**Comment by Nabla128k** [comment]
oh, sorry it seems I have wrong paths of custom_widgets and custom_css folders... which is really hard to find where to place it (I don't run official HASS distro, so it's even more complicated :-)
